// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oefening1.Data;

#nullable disable

namespace Oefening1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306121839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oefening1.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Description = "Classic leather sneakers.",
                            Name = "Retro High-Tops",
                            Price = 120f
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Description = "Breathable mesh with arch support.",
                            Name = "Performance Runners",
                            Price = 89.99f
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Description = "Suede slip-ons for business casual.",
                            Name = "Casual Loafers",
                            Price = 75f
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Description = "Waterproof and rugged terrain ready.",
                            Name = "Hiking Boots",
                            Price = 145.5f
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Description = "Soft-wash cotton graphic tee.",
                            Name = "Vintage Band Tee",
                            Price = 25f
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Description = "Plain white essential tee.",
                            Name = "Basic V-Neck",
                            Price = 15f
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Description = "Limited edition artist print.",
                            Name = "Graphic Streetwear",
                            Price = 45f
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Description = "Lightweight layering piece.",
                            Name = "Long Sleeve Jersey",
                            Price = 30f
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            Description = "Stretch khaki for all-day comfort.",
                            Name = "Slim Fit Chinos",
                            Price = 55f
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            Description = "Raw indigo denim, straight leg.",
                            Name = "Selvedge Denim",
                            Price = 110f
                        },
                        new
                        {
                            Id = 11,
                            Category = 2,
                            Description = "Multi-pocket durable canvas.",
                            Name = "Cargo Work Pants",
                            Price = 65f
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            Description = "Tailored wool blend.",
                            Name = "Dress Slacks",
                            Price = 95f
                        },
                        new
                        {
                            Id = 13,
                            Category = 3,
                            Description = "Quick-dry fabric for gym sessions.",
                            Name = "Athletic Mesh Shorts",
                            Price = 22.5f
                        },
                        new
                        {
                            Id = 14,
                            Category = 3,
                            Description = "Classic 7-inch inseam.",
                            Name = "Flat-Front Chino Shorts",
                            Price = 35f
                        },
                        new
                        {
                            Id = 15,
                            Category = 3,
                            Description = "Rugged outdoor shorts.",
                            Name = "Cargo Shorts",
                            Price = 38f
                        },
                        new
                        {
                            Id = 16,
                            Category = 3,
                            Description = "",
                            Name = "Board Shorts",
                            Price = 40f
                        },
                        new
                        {
                            Id = 17,
                            Category = 4,
                            Description = "Fleece-lined charcoal hoodie.",
                            Name = "Heavyweight Hoodie",
                            Price = 60f
                        },
                        new
                        {
                            Id = 18,
                            Category = 4,
                            Description = "Pique knit sporty layer.",
                            Name = "Quarter-Zip Pullover",
                            Price = 52f
                        },
                        new
                        {
                            Id = 19,
                            Category = 4,
                            Description = "Minimalist embroidered logo.",
                            Name = "Crewneck Sweater",
                            Price = 48f
                        },
                        new
                        {
                            Id = 20,
                            Category = 4,
                            Description = "Water-resistant tech fleece.",
                            Name = "Zip-up Windbreaker",
                            Price = 75f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
